version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    networks:
      - auth_net
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "mydb"]
      interval: 5s
      retries: 5

  migrate:
    image: flyway/flyway:7.8.1-alpine
    networks:
      - auth_net
    command: migrate -url=jdbc:postgresql://postgres:5432/mydb -user=admin -password=qwerty
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
  server:
    build: .
    container_name: server
    networks:
      - auth_net
    ports:
      - "8080:8080"
    environment:
      - DBHost=postgres
      - DBPort=5432
      - DBUser=admin
      - DBPass=qwerty
      - DBName=mydb
      - DBMode=disable
      - TOKEN_KEY=${TOKEN_KEY}
    depends_on:
      - postgres

networks:
  auth_net:
    driver: bridge
volumes:
  postgres_data: